Port stateroot changes to master
nspcc-dev/neo-go pull request #1385
Opened 2020-09-03 14:06 UTC by fyrchik

Close #1377 .

Changes:
1. `stateRootEnabled` is no longer used.
2. Items are stored by contract ID.
3. There are now 2 P2P commands instead of 3.

Testing done: `go test`, `make env_up`.

2020-09-19 20:08 UTC, roman-khimov requested changes
It looks good, but maybe it's better to wait a little for neo-project to decide how it really is gonna look like for Neo 3.

2020-09-23 12:40 UTC, AnnaShaleva approved these changes

2020-09-23 12:40 UTC, AnnaShaleva commented on pkg/rpc/server/server.go
> +		return nil, response.NewRPCError("Invalid parameter.", "", nil)
`return nil, response.ErrInvalidParams`?

2020-09-23 12:40 UTC, AnnaShaleva commented on pkg/rpc/client/rpc_test.go
> +	"getstateroot": {
A test for error case can also be added to `rpcClientErrorCase` in order to cover error after `c.PerformRequest`.

2020-11-20 15:27 UTC, roman-khimov commented
#1500 was merged making this really obsolete. Any new Neo 3 changes wrt this topic are to be implemented in separate PRs based on current master branch.

2020-11-20 15:27 UTC, closed without merging