core: add validation to policy methods
nspcc-dev/neo-go pull request #1454
Opened 2020-10-02 15:17 UTC by AnnaShaleva

closes #1442

2020-10-02 15:38 UTC, roman-khimov requested changes
Good, but `block` changes need a bit better coverage.

2020-10-05 13:45 UTC, fyrchik commented on pkg/core/block/block_test.go
> +		require.True(t, errors.Is(ErrMaxContentsPerBlock, testserdes.DecodeBinary(data, new(Block))))
This should be the other way `errors.Is(testserdes...., ErrMaxContentsPerBlock)`

2020-10-05 13:46 UTC, fyrchik approved these changes

2020-10-05 16:09 UTC, roman-khimov approved these changes

2020-10-05 16:09 UTC, merged