rpc, core: add FaultException to AppExecResult and Invoke* results
nspcc-dev/neo-go pull request #1462
Opened 2020-10-05 14:12 UTC by AnnaShaleva

Closes #1440

2020-10-05 14:19 UTC, fyrchik commented on pkg/core/state/notification_event.go
> +	w.WriteString(hex.EncodeToString([]byte(e)))
Why do we need to encode this in hex?

2020-10-05 14:19 UTC, fyrchik commented on pkg/core/state/notification_event.go
> +	FaultException error
I think, string is ok here, because we use it as string anyway and `encode/decode` conversion is lossy.

2020-10-05 14:19 UTC, fyrchik commented on pkg/core/state/notification_event_test.go
> +	"github.com/syndtr/goleveldb/leveldb/errors"
Wrong import.

2020-10-05 15:20 UTC, AnnaShaleva commented on pkg/core/state/notification_event.go
> +	w.WriteString(hex.EncodeToString([]byte(e)))
Fixed, just bytes now.

2020-10-06 16:19 UTC, roman-khimov requested changes

2020-10-06 16:19 UTC, roman-khimov commented on pkg/rpc/client/policy.go
> +		return 0, errors.New("result stack is sempty")
Maybe we need some
```
err := getInvocationError(*result.Invoke)
if err != nil {
    return err
}
```
To avoid this massive duplication?

2020-10-08 12:07 UTC, roman-khimov requested changes

2020-10-08 12:07 UTC, roman-khimov commented on pkg/rpc/client/rpc.go
> +			if err != nil {
This should be the first check then, it it's not `nil`, `res` might be `nil` easily and this code would fail earlier than expected.

2020-10-08 13:20 UTC, roman-khimov approved these changes

2020-10-08 13:20 UTC, merged