rpc: add `verifywitness` RPC-method
nspcc-dev/neo-go pull request #1524
Opened 2020-11-06 12:26 UTC by AnnaShaleva

Implement https://github.com/neo-project/neo-modules/pull/378#issuecomment-722652859 proposal.

2020-12-15 09:39 UTC, roman-khimov commented
@fyrchik, please review.

2020-12-15 11:41 UTC, fyrchik requested changes
We also need to change `Client.AddNetworkFee()` to use this RPC instead of `invokefunction`.

2020-12-15 11:41 UTC, fyrchik commented on pkg/rpc/client/rpc_test.go
> +	"invokecontractverify": {
Can we add this test without prebuilt response to `server/client_test.go` instead?

2020-12-15 11:41 UTC, fyrchik commented on pkg/rpc/server/server_test.go
> +			params: fmt.Sprintf(`["%s", []]`, strings.ReplaceAll(verifyContractHash, "a", "b")),
This is a bit unreliable, smth like `util.Uint160{}.String()` is more suitable, I believe.

2020-12-15 11:41 UTC, fyrchik commented on pkg/rpc/server/server.go
> +func (s *Server) runScriptInVM(script []byte, tx *transaction.Transaction, t trigger.Type) (*result.Invoke, *response.Error) {
Let the trigger be first like in other places?

2020-12-15 11:41 UTC, fyrchik commented on pkg/rpc/server/server.go
> +	if len(tx.Signers) == 0 {
C# module passes `null` transaction if signers are not present.

2020-12-19 21:22 UTC, roman-khimov commented
@fyrchik, please review.

2020-12-21 07:09 UTC, fyrchik approved these changes

2020-12-21 07:36 UTC, merged