native: unify committee checks
nspcc-dev/neo-go pull request #1695
Opened 2021-01-28 15:17 UTC by fyrchik

Fail execution if tx is not signed by committee.
Close #1694 .
Related #1678 (set/getprice test).

2021-01-28 16:14 UTC, AnnaShaleva requested changes
1. We also have `setMaxNotValidBeforeDelta` method for native Notary. Could you, please, fix it too?
2. Native Management's `setMinimumDeploymentFee` also has the same problem, but it is not fixed in C#. I think we may leave a comment about it in C# repo.

2021-01-29 07:51 UTC, fyrchik commented
@AnnaShaleva (1) is fixed and `setMinimumDeploymentFee` was void from the start in the C# node.

2021-01-29 08:15 UTC, AnnaShaleva approved these changes

2021-01-29 08:58 UTC, roman-khimov approved these changes

2021-01-29 08:58 UTC, merged