network: add logs for different RelayTx errors
nspcc-dev/neo-go pull request #1757
Opened 2021-02-17 13:34 UTC by AnnaShaleva

2021-02-17 14:16 UTC, fyrchik approved these changes

2021-02-17 16:02 UTC, roman-khimov requested changes

2021-02-17 16:02 UTC, roman-khimov commented on pkg/network/server.go
> +func (s *Server) verifyAndPoolTX(t *transaction.Transaction) (RelayReason, error) {
Return `error` here.

2021-02-17 16:02 UTC, roman-khimov commented on pkg/network/server.go
> +func (s *Server) RelayTxn(t *transaction.Transaction) (RelayReason, error) {
And here.

2021-02-17 16:02 UTC, roman-khimov commented on pkg/rpc/server/server.go
> +	return getRelayResult(r, tx.Hash())
The deal with this error here (in `getRelayResult`), RPC server imports `core` anyway.

2021-02-17 16:02 UTC, roman-khimov commented on pkg/network/server.go
> +					return fmt.Errorf("can't relay completed notary transaction: hash %s, reason: %s, error message: %w", tx.Hash().StringLE(), r.String(), err)
And just wrap the error here.

2021-02-17 16:02 UTC, roman-khimov commented on pkg/network/server.go
> +					zap.String("reason", r.String()),
Log here.

2021-02-18 09:34 UTC, AnnaShaleva commented on pkg/network/server.go
> +func (s *Server) verifyAndPoolTX(t *transaction.Transaction) (RelayReason, error) {
Fixed, looks better now.

2021-02-18 09:36 UTC, roman-khimov commented on pkg/network/server.go
> +					zap.String("error", err.Error()))
`zap.Error()`?

2021-02-18 10:13 UTC, roman-khimov approved these changes

2021-02-18 10:13 UTC, merged