Move some Policy settings to config
nspcc-dev/neo-go pull request #1759
Opened 2021-02-17 15:37 UTC by fyrchik

Close #1742 .

1. `MaxTransactionsPerBlock` is moved to config.
2. `MaxBlockSize` and `MaxBlockSystemFee` are removed. See also https://github.com/neo-project/neo/pull/2300/files#r571941755

2021-02-18 07:57 UTC, AnnaShaleva requested changes

2021-02-18 07:57 UTC, AnnaShaleva commented on pkg/core/blockchain.go
> +		log.Info("MaxTraceableBlocks is not set or wrong, using default value",
MaxTransactionsPerBlock

2021-02-18 09:44 UTC, fyrchik commented on pkg/core/blockchain.go
> +		log.Info("MaxTraceableBlocks is not set or wrong, using default value",
Fixed.

2021-02-26 14:05 UTC, AnnaShaleva approved these changes

2021-03-04 21:21 UTC, roman-khimov approved these changes

2021-03-04 21:22 UTC, merged