compiler: disallow `runtime.Notify` in `Verify` function
nspcc-dev/neo-go pull request #1995
Opened 2021-06-04 08:56 UTC by fyrchik

Only direct invocations are considered. The check can be disabled
with '--no-events' compiler option.

Close #1994 .

I have been thinking about introducing generic warnings mechanism but stopped, because our compiler doesn't seem _that_ complicated. It could be used e.g. in #1990, but I haven't yet come up with more cases for it to be useful.

2021-06-04 11:46 UTC, roman-khimov commented on pkg/compiler/codegen.go
> +	return decl.Name.Name == "Verify" && decl.Recv == nil &&
It can have arguments.

2021-06-04 11:46 UTC, roman-khimov commented on pkg/compiler/codegen.go
> +		decl.Type.Results.NumFields() == 1
And resulting type is always bool.

2021-06-04 13:50 UTC, fyrchik commented on pkg/compiler/codegen.go
> +	return decl.Name.Name == "Verify" && decl.Recv == nil &&
Yes, it _can_.

2021-06-04 17:55 UTC, roman-khimov commented on pkg/compiler/codegen.go
> +		decl.Type.Results.NumFields() == 1
So how about `Results.List[0].Type`?

2021-06-04 20:14 UTC, AnnaShaleva requested changes

2021-06-04 20:14 UTC, AnnaShaleva commented on pkg/compiler/compiler.go
> +	b, di, err := CompileWithOptions(src, nil, o)
Maybe we can add a separate flag to the `contract compile` command to be able to use this option from the outside? Like it is done for `NoStandardCheck` and `NoEventsCheck`.

2021-06-04 20:17 UTC, AnnaShaleva commented on pkg/compiler/compiler.go
> +	b, di, err := CompileWithOptions(src, nil, o)
Oh, I see that `no-events` is used for that.

2021-06-04 20:21 UTC, AnnaShaleva approved these changes

2021-06-06 06:31 UTC, fyrchik commented on pkg/compiler/codegen.go
> +		decl.Type.Results.NumFields() == 1
Fixed.

2021-06-06 08:34 UTC, roman-khimov approved these changes

2021-06-06 08:34 UTC, merged