rpc: wrap calculatenetworkfee result in a structure
nspcc-dev/neo-go pull request #1998
Opened 2021-06-04 17:46 UTC by roman-khimov

C#:
{
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "networkfee": "1185120"
  }
}

Go:
{
  "id": 2,
  "jsonrpc": "2.0",
  "result": 1185120
}

Thanks @csmuller for finding it.

2021-06-04 20:33 UTC, AnnaShaleva requested changes

2021-06-04 20:33 UTC, AnnaShaleva commented on pkg/rpc/client/rpc.go
> +		resp   = new(result.NetworkFee)
Then we don't need `&` two lines below.

2021-06-04 20:38 UTC, roman-khimov commented on pkg/rpc/client/rpc.go
> +		resp   = new(result.NetworkFee)
Fixed

2021-06-07 06:51 UTC, AnnaShaleva approved these changes

2021-06-07 06:53 UTC, merged