interop/runtime: add `System.Runtime.GetNetwork`, fix #2038
nspcc-dev/neo-go pull request #2043
Opened 2021-07-06 13:29 UTC by fyrchik

Fix #2038.

2021-07-08 07:12 UTC, AnnaShaleva requested changes

2021-07-08 07:12 UTC, AnnaShaleva commented on pkg/core/interop/runtime/util.go
> +func GetNetwork(ic *interop.Context) error {
We also need an interop wrapper for the compiler.

2021-07-09 13:57 UTC, AnnaShaleva approved these changes

2021-07-12 07:46 UTC, roman-khimov approved these changes

2021-07-12 07:46 UTC, merged