Tune fixed GAS limits
nspcc-dev/neo-go pull request #2055
Opened 2021-07-12 10:13 UTC by fyrchik

Close #2037 .

2021-07-12 12:13 UTC, roman-khimov requested changes
Notice that headers have `3_00000000L` limit.

2021-07-13 07:49 UTC, AnnaShaleva requested changes

2021-07-13 07:49 UTC, AnnaShaleva commented on pkg/core/blockchain.go
> +	verificationGasLimit                   = 1_50000000 // 1.5 GAS
We also need to increase GAS for headers verification https://github.com/neo-project/neo/pull/2493/files#diff-b79f1f745f19a6d42055888b9cf96063394726ba2603a25af58547313f6d7518R222-R223

2021-07-13 07:49 UTC, AnnaShaleva commented on pkg/core/blockchain.go
> +	verificationGasLimit                   = 1_50000000 // 1.5 GAS
Oh, I see it's already mentioned in https://github.com/nspcc-dev/neo-go/pull/2055#pullrequestreview-704039053

2021-07-13 19:18 UTC, AnnaShaleva commented
> While we decode `CMDHeaders` payload, we don't use it in any way. It is added in #2019 though.

So I can fix it in #2019 then.

2021-07-13 19:30 UTC, roman-khimov commented
I'd rather have it there (it's quite a simple change that technically has nothing to do with the essence of #2019). #2019 might be postponed after 0.96.0.

2021-07-16 08:07 UTC, roman-khimov commented
@fyrchik?

2021-07-16 11:48 UTC, fyrchik commented
Sorry, forgot to push changes.

2021-07-16 12:15 UTC, roman-khimov approved these changes

2021-07-16 13:52 UTC, AnnaShaleva approved these changes

2021-07-16 13:53 UTC, merged