vm/cli: add public key -> address conversion, fix #2121
nspcc-dev/neo-go pull request #2125
Opened 2021-08-12 13:40 UTC by fyrchik

Signed-off-by: Evgeniy Stratonikov <evgeniy@nspcc.ru>

2021-08-12 15:06 UTC, roman-khimov requested changes
Tests.

2021-08-13 03:33 UTC, AnnaShaleva commented on pkg/vm/cli/cli.go
> +		if pub, err := keys.NewPublicKeyFromBytes(rawStr, elliptic.P256()); err == nil {
The documentation example for `util convert` should also be updated.

2021-08-13 08:05 UTC, AnnaShaleva approved these changes

2021-08-13 08:49 UTC, roman-khimov approved these changes

2021-08-13 08:49 UTC, merged