compiler: optimize tests
nspcc-dev/neo-go pull request #2382
Opened 2022-03-02 06:48 UTC by fyrchik

The longest in compiler tests are the ones that check some specific construction using it in multiple ways.
We can put such tests in functions in a single file.

```
# master
ok      github.com/nspcc-dev/neo-go/pkg/compiler        15.357s
# PR
ok      github.com/nspcc-dev/neo-go/pkg/compiler        11.732s
```

Related #2379 .

Signed-off-by: Evgeniy Stratonikov <evgeniy@nspcc.ru>

2022-03-03 13:02 UTC, roman-khimov approved these changes

2022-03-03 13:04 UTC, roman-khimov commented on pkg/compiler/for_test.go
> +	for i, tc := range testCases {
`forLoopTestCases`

2022-03-03 13:04 UTC, roman-khimov commented on pkg/compiler/for_test.go
> +	for i, tc := range binaryExprTestCases {
`forLoopTestCases`

2022-03-03 13:06 UTC, roman-khimov requested changes

2022-03-03 13:06 UTC, roman-khimov commented on pkg/compiler/binary_expr_test.go
> +	for i, tc := range testCases {
`binaryExprTestCases`

2022-03-04 10:17 UTC, fyrchik commented on pkg/compiler/for_test.go
> +	for i, tc := range testCases {
Fixed.

2022-03-04 10:17 UTC, fyrchik commented on pkg/compiler/for_test.go
> +	for i, tc := range binaryExprTestCases {
Fixed.

2022-03-04 10:18 UTC, fyrchik commented on pkg/compiler/binary_expr_test.go
> +	for i, tc := range testCases {
Fixed

2022-03-04 13:14 UTC, roman-khimov commented on pkg/compiler/for_test.go
> +	for i, tc := range testCases {
Not really.

2022-03-04 14:55 UTC, fyrchik commented on pkg/compiler/for_test.go
> +	for i, tc := range testCases {
Missed the second line, fixed.

2022-03-04 15:48 UTC, AnnaShaleva approved these changes

2022-03-04 15:55 UTC, roman-khimov approved these changes

2022-03-04 15:55 UTC, merged