cli: allow to provide single node config file
nspcc-dev/neo-go pull request #3014
Opened 2023-05-12 13:55 UTC by AnnaShaleva

Close #2978.

2023-05-12 18:26 UTC, roman-khimov requested changes

2023-05-12 18:26 UTC, roman-khimov commented on cli/options/options.go
> +	cli.BoolFlag{Name: "testnet, t", Usage: "use testnet network configuration (if --config-path option is specified)"},
That's not exactly the case. It's rather `if --config-file is not specified`. I'd expect `neo-go node -m` to still work the same way as before.

2023-05-16 09:31 UTC, AnnaShaleva commented on cli/options/options.go
> +	Usage: "path to directory with configuration files (may be overridden by --config-file option)",
Fixed.

2023-05-16 10:05 UTC, roman-khimov commented on cli/options/options.go
> +	Usage: "path to a single node configuration file (overrides --config-path option)",
It's just a configuration file. It inevitably has some network (magic) inside of it.

2023-05-16 10:07 UTC, roman-khimov commented on cli/options/options.go
> +	var configPath = "./config"
I do love `var` definitions, but I also love consistency. Here you change from `:=` to `var` while introducing another `:=`. It'd be nice to have some similarity.

2023-05-16 10:24 UTC, AnnaShaleva commented on cli/options/options.go
> +	Usage: "path to a single node configuration file (overrides --config-path option)",
Finally, it's just a `node configuration file`, fixed everywhere.

2023-05-16 11:42 UTC, roman-khimov approved these changes

2023-05-16 11:42 UTC, merged